
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *

* 
* 
 */
public class Loggin extends javax.swing.JFrame {

    /**
     * Creates new form Loggin
     */
    public Loggin() {
        initComponents();
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
               redimensionarLogo();
            }
        });

        this.getContentPane().setBackground(java.awt.Color.WHITE);
        this.setLocationRelativeTo(null);
        personalizarComponentes(); 
        
        // Agrega el ActionListener para el botón
        Ingresar_Bottom.addActionListener(evt -> validarLogin());
    }

    private void validarLogin() {
        
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectas. Intenta de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
        
    }

    
 private void personalizarComponentes() {
    // Centrar la ventana en pantalla
    setLocationRelativeTo(null);

    // Personalizar el layout
    getContentPane().setLayout(new java.awt.GridBagLayout());

    // Ejemplo: Cambiar el color del fondo del panel principal
    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    // Agregar más personalizaciones según necesites
}
    
    private void redimensionarLogo() {
    if (triangulo_con_logo.getIcon() != null) {
        ImageIcon icon = new ImageIcon(getClass().getResource("/iconos/triangulo_con_logo.png"));
        Image img = icon.getImage();

        int ancho = triangulo_con_logo.getWidth();
        int alto = triangulo_con_logo.getHeight();

        if (ancho > 0 && alto > 0) {
            Image newImg = img.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
            triangulo_con_logo.setIcon(new ImageIcon(newImg));
        }
    }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IngresarUsuario = new javax.swing.JTextField();
        textogenerico = new javax.swing.JLabel();
        Ingresa = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        IngresarPassword = new javax.swing.JTextField();
        Ingresar_Bottom = new javax.swing.JButton();
        Registrar_Bottom = new javax.swing.JButton();
        triangulo_con_logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        IngresarUsuario.setBackground(new java.awt.Color(0, 0, 0));
        IngresarUsuario.setForeground(new java.awt.Color(255, 255, 255));

        textogenerico.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        textogenerico.setText("inicia sesión para continuar");

        Ingresa.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Ingresa.setText("Ingresa");

        Password.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Password.setText("Contraseña");

        Usuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Usuario.setText("Usuario");

        IngresarPassword.setBackground(new java.awt.Color(0, 0, 0));
        IngresarPassword.setForeground(new java.awt.Color(255, 255, 255));

        Ingresar_Bottom.setBackground(new java.awt.Color(0, 0, 0));
        Ingresar_Bottom.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        Ingresar_Bottom.setForeground(new java.awt.Color(255, 255, 255));
        Ingresar_Bottom.setText("INGRESAR");

        Registrar_Bottom.setBackground(new java.awt.Color(0, 0, 0));
        Registrar_Bottom.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        Registrar_Bottom.setForeground(new java.awt.Color(255, 255, 255));
        Registrar_Bottom.setText("REGISTRARSE");
        Registrar_Bottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrar_BottomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Password)
                    .addComponent(IngresarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IngresarPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuario)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(textogenerico))
                            .addComponent(Ingresa))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Registrar_Bottom)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Ingresar_Bottom)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Ingresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textogenerico, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngresarPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngresarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Ingresar_Bottom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Registrar_Bottom)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        triangulo_con_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/triangulo_con_logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(triangulo_con_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(triangulo_con_logo))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Registrar_BottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrar_BottomActionPerformed
        this.dispose();
        // Abre la ventana de selección de usuario
        new SeleccionarTipoUsuario().setVisible(true);
    }//GEN-LAST:event_Registrar_BottomActionPerformed

    
    /**
     * @param args the command line arguments"
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new Loggin().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ingresa;
    private javax.swing.JTextField IngresarPassword;
    private javax.swing.JTextField IngresarUsuario;
    private javax.swing.JButton Ingresar_Bottom;
    private javax.swing.JLabel Password;
    private javax.swing.JButton Registrar_Bottom;
    private javax.swing.JLabel Usuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textogenerico;
    private javax.swing.JLabel triangulo_con_logo;
    // End of variables declaration//GEN-END:variables
}
