/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author arya
 */
public class SeleccionarTipoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionarTipoUsuario
     */
    public SeleccionarTipoUsuario() {
        initComponents();
        this.getContentPane().setBackground(java.awt.Color.WHITE);
        this.setLocationRelativeTo(null);
        personalizarComponentes(); 
        configurarBotones(); 
    }
    
    private void configurarBotones() {
    // Acción para el botón "Volver a la página de inicio"
    VolverAlMenu.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            new Loggin().setVisible(true); // Abre la ventana principal
            dispose(); // Cierra esta ventana
        }
    });
            
    RegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            new RegistrarEmpleado().setVisible(true); // Abre la ventana principal
            dispose(); // Cierra esta ventana
        }
    }
    
    );

      RegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            new RegistrarCliente().setVisible(true); // Abre la ventana principal
            dispose(); // Cierra esta ventana
        }
    }
    
    );
    
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
private void personalizarComponentes() {
    // Centrar la ventana en pantalla
    setLocationRelativeTo(null);

    // Personalizar el layout
    getContentPane().setLayout(new java.awt.GridBagLayout());
    java.awt.GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();

    // Ejemplo: Cambiar el color del fondo del panel principal
    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    // Personalización del botón "Volver"
    VolverAlMenu.setBackground(new java.awt.Color(255, 255, 255)); // Fondo blanco
    VolverAlMenu.setBorderPainted(false); // Sin borde
    VolverAlMenu.setContentAreaFilled(false); // Sin relleno
    VolverAlMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Cursor tipo mano
}
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextoGenerico = new javax.swing.JLabel();
        RegistrarEmpleado = new javax.swing.JButton();
        RegistrarCliente = new javax.swing.JButton();
        VolverAlMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TextoGenerico.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        TextoGenerico.setText("Elige tu tipo de usuario");

        RegistrarEmpleado.setBackground(new java.awt.Color(0, 0, 0));
        RegistrarEmpleado.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        RegistrarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarEmpleado.setText("Empleado");

        RegistrarCliente.setBackground(new java.awt.Color(0, 0, 0));
        RegistrarCliente.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        RegistrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarCliente.setText("Cliente");

        VolverAlMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        VolverAlMenu.setText("Volver");
        VolverAlMenu.setBorder(null);
        VolverAlMenu.setBorderPainted(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(RegistrarEmpleado)
                .addGap(111, 111, 111)
                .addComponent(RegistrarCliente)
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TextoGenerico)
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(VolverAlMenu)
                        .addGap(289, 289, 289))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(TextoGenerico)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarEmpleado)
                    .addComponent(RegistrarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VolverAlMenu)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarTipoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarTipoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarTipoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarTipoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionarTipoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegistrarCliente;
    private javax.swing.JButton RegistrarEmpleado;
    private javax.swing.JLabel TextoGenerico;
    private javax.swing.JButton VolverAlMenu;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
